import './theme.js';
import '../styles/tokens.css';
import '../styles/layout.css';
import { route, renderRoute, navigate } from './router.js';
import { applyTheme } from './theme.js';
import { ensureUiRoot } from './ui.js';
import { renderLanding } from '../pages/landing.js';
import { renderDemo } from '../pages/demo.js';
import { renderAuth } from '../pages/auth.js';
import { renderTutorial } from '../pages/tutorial.js';
import { observeAuth } from '../services/firebase.js';
import { renderHome } from '../pages/home.js';
import { renderNewChampionship } from '../pages/new-championship.js';
import { renderChampionship } from '../pages/championship.js';
import { renderPlans } from '../pages/plans.js';
import { renderPublicChampionship } from '../pages/public-championship.js';
import { renderRegistration } from '../pages/registration.js';
import { renderSuperadmin } from '../pages/superadmin.js';
import { renderPublication } from '../pages/publication.js';

const root = document.querySelector('#app');
applyTheme();
ensureUiRoot();
route('/', () => renderLanding(root));
route('/login', () => renderAuth(root, 'login'));
route('/register', () => renderAuth(root, 'register'));
route('/tutorial', () => renderTutorial(root));
route('/demo', () => renderDemo(root));
route('/campeonatos/novo', () => renderNewChampionship(root));
route('/planos', () => renderPlans(root));
route('/superadmin', () => renderSuperadmin(root));
route('/publicacao', () => renderLanding(root));
const dynamicRoute = () => { const publicationMatch = window.location.pathname.match(/^\/publicacao\/([^/]+)$/); if (publicationMatch) return renderPublication(root, publicationMatch[1]); const registrationMatch = window.location.pathname.match(/^\/inscrever\/([^/]+)$/); if (registrationMatch) return renderRegistration(root, registrationMatch[1]); const publicMatch = window.location.pathname.match(/^\/publico\/([^/]+)$/); if (publicMatch) return renderPublicChampionship(root, publicMatch[1]); const match = window.location.pathname.match(/^\/campeonatos\/([^/]+)$/); if (match && match[1] !== 'novo') return renderChampionship(root, match[1]); if (window.location.pathname === '/campeonatos/novo') return renderNewChampionship(root); renderRoute(); };
window.__arenaRenderRoute = dynamicRoute;
window.addEventListener('popstate', dynamicRoute);
dynamicRoute();
observeAuth((user) => { if (user && ['/login', '/register'].includes(window.location.pathname)) { window.history.replaceState({}, '', '/'); renderHome(root); } if (user && window.location.pathname === '/') renderHome(root); if (!user && window.location.pathname.startsWith('/campeonatos/')) navigate('/login'); });
